### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by shohi**
Also reformat some paragraphs.

### CODE REVIEW

**Comment by psionic-k** [comment]
Thanks for spotting the inconsistency.  Can you fix it the other way, going to all `transient--simple-child`?  I don't think anyone's interested in that prefix when called independently.  Don't need it in M-x commands.

**Comment by shohi** [comment]
Sure, that makes sense, will change it to `ts--simple-child`

**Comment by psionic-k** [comment]
Thanks for changes!  Hope you enjoy the package.

**Comment by shohi** [comment]
Thank you for writing such a great guide!

**Pull request merged**
