### PR TITLE
Fix inapt demo

### LINKED ISSUE #19: Fix `inapt` example
Thank you for this showcase!!

Did you mean to use `:inapt-if-not` instead of `:if-not` [here](https://github.com/positron-solutions/transient-showcase#inapt-temporarily-unavailable)?

### PR DESCRIPTION
**Pull request by josephmturner**
Resolves #19.

### CODE REVIEW

**Comment by psionic-k** [comment]
Process nit:  needs signoff.  The contrib guide should move you right along.

Other than that, LGTM

**Comment by josephmturner** [comment]
> Process nit: needs signoff.

Done. Thanks!

**Review by psionic-k — APPROVED** [review]

**Comment by psionic-k** [comment]
Sorry I didn't notice, but the commit was also missing GPG signature.  Should also be covered in the contrib doc.

**Comment by josephmturner** [comment]
> Sorry I didn't notice, but the commit was also missing GPG signature. Should also be covered in the contrib doc.

https://github.com/positron-solutions/transient-showcase/commit/b455edd25288bcc55d4ca6b533089712cf9d8087 should have my signature.

**Comment by psionic-k** [comment]
Ah, check https://github.com/positron-solutions/transient-showcase/pull/20/commits

Your email on the commit sig isn't verified yet.

**Comment by josephmturner** [comment]
> Your email on the commit sig isn't verified yet.

I have done as you asked, but note that you are asking me to do something which is not explicitly specified in `CONTRIBUTING.org`. `CONTRIBUTING.org` tells contributors to sign commits, but it says nothing about adding GPG keys to Github. 

If you insist that signatures be "verified" by Github, I suggest that you say so in `CONTRIBUTING.org`. In addition to the existing link to [this help page on signing commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits), you might additionally link to [this help page on adding GPG keys to Github](https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account).

However, I ask that you reconsider making Microsoft the central trust authority for `transient-showcase`.

**Comment by psionic-k** [comment]
> However, I ask that you reconsider making Microsoft the central trust authority for `transient-showcase`.

Pretty funny how that turned out.

There's a longer discussion brewing about trust authorities, but this is a case of using merely sufficient things until better things are available.

**Comment by josephmturner** [comment]
@psionic-k  sorry for my grumpiness earlier :)

**Pull request merged**
