### PR TITLE
fix link description for transient-switch match lin

### PR DESCRIPTION
**Pull request by nverno**
Simple typo fix for transient-switch link description

### CODE REVIEW

**Comment by psionic-k** [comment]
Not sure what's ambiguous here.  The preceding line mentions both switch and option.  Anyway the change makes the line inconsistent.

**Comment by nverno** [comment]
the link description says `transient-option` but the link is to `transient-switch`...

**Comment by psionic-k** [comment]
It's two different links.  The change makes it inconsistent.

**Comment by nverno** [comment]
I just changed the link description of the second link to match it's target - `transient-switch`. 

Before change it looks like (both links have same description)
before
And after it looks like
after

I thought that was what you intended there

**Comment by psionic-k** [comment]
Red green colorblind.  LGTM

**Comment by psionic-k** [comment]
I'll fix up this stupid sign-off check.  I think it results from local git config not matching your github config, but as long as the email addresses match, I consider it valid.

```sign-off not found for commit author: nverno noah.v.peart@gmail.com; found: ['Noah Peart <noah.v.peart@gmail.com>']```

Probably switching the bot back.  Anyway, this will get merged with attribution intact.

**Comment by nverno** [comment]
Thanks, sorry about the confusion :/.  I fixed the sign-off

**Pull request merged**
